"use client";

import Header from "@/components/sections/Header";
import "../globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/sections/Footer";
import PageWrapper from "@/components/commons/PageWrapper";
import Section from "@/components/commons/Section";
import Container from "@/components/commons/Container";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Poppins } from "next/font/google";
import { createContext, useEffect, useState } from "react";
import SecondaryHeader from "@/components/sections/SecondaryHeader";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const NavCtx = createContext();

export default function RootLayout({ children }) {
  const [transparent, setTransparent] = useState(true);
  addEventListener("scroll", (e) => {
    if (Number(window.scrollY) > 50) {
      setTransparent(false);
    } else {
      setTransparent(true);
    }
  });

  return (
    <html lang="en">
      <style jsx global>{`
        html {
          font-family: ${poppins.style.fontFamily};
        }
      `}</style>
      <script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>
      <body className={inter.className}>
        <NavCtx.Provider
          value={{
            transparent: transparent,
          }}>
          <PageWrapper>
            <SecondaryHeader />
            {children}
            <Section className="bg-[#2681EB]">
              <Container className=" pt-[2rem] pb-[2rem] lg:pt-[6rem] lg:pb-[5rem]">
                <Footer />
              </Container>
            </Section>
          </PageWrapper>
        </NavCtx.Provider>
      </body>
    </html>
  );
}
